schema_version: 1

context:
  version: "0.3.0"

package:
  name: confingy
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/c/confingy/confingy-${{ version }}.tar.gz
  sha256: d60c43e96f49a0190974c4482cd09aa37882d815b0d011b0e6355991d2b9f081

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - confingy = confingy.cli:main

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - pydantic >=2
    - typer >=0.19.0
    - typing_extensions >=4.6.0

tests:
  - python:
      imports:
        - confingy
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - confingy --help

about:
  summary: An implicit configuration system
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://pypi.org/project/confingy/

extra:
  recipe-maintainers:
    - thewchan
